services:
  database-test:
    container_name: database-test
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: asdf
      POSTGRES_DB: api-test

#using based on dockerfile
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: app-backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://database-test:5432/api-test
#      SPRING_DATASOURCE_USERNAME: asdf
#      SPRING_DATASOURCE_PASSWORD: asdf
#    depends_on:
#      - database-test

#using from docker hub
  backend:
    image: nowyoucanseeme/spring-api-test:0.0.4
    container_name: app-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-test:5432/api-test
      SPRING_DATASOURCE_USERNAME: asdf
      SPRING_DATASOURCE_PASSWORD: asdf
    depends_on:
      - database-test